name: Test
on:
  pull_request:
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run lint check
      run: yarn run lint
  Unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn test --coverage
    # - name: Upload coverage 📤
    #   uses: codecov/codecov-action@v1
    #   with:
    #     file: coverage/lcov.info
    #     fail_ci_if_error: true
  Build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install --frozen-lockfile
    - name: Run build check
      run: yarn run build
